# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField(default=0, verbose_name='Latitud')),
                ('lon', models.IntegerField(default=0, verbose_name='Longitud')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciu_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clima.Ciudad', verbose_name='Ciudad')),
                ('coor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clima.Coordenadas', verbose_name='Coordenadas')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(default=0, verbose_name='Temperatura')),
                ('humedad', models.IntegerField(default=0, verbose_name='Humedad')),
                ('uv', models.CharField(max_length=20, verbose_name='Rayo uv')),
                ('pres', models.IntegerField(default=0, verbose_name='Presion')),
                ('s_ter', models.IntegerField(default=0, verbose_name='Sensacion Termica')),
                ('desc', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('fec', models.CharField(max_length=100, verbose_name='Fecha')),
            ],
        ),
        migrations.AddField(
            model_name='historico',
            name='medicion_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clima.Medicion', verbose_name='Medicion'),
        ),
    ]
