# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField(default=0, verbose_name='Latitud')),
                ('lon', models.IntegerField(default=0, verbose_name='Longitud')),
                ('fcs', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(default=0, verbose_name='Temperatura')),
                ('humedad', models.IntegerField(default=0, verbose_name='Humedad')),
                ('viento', models.CharField(max_length=20, verbose_name='Viento')),
                ('desc', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('fcs', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('est', models.BooleanField(default=False)),
                ('fcs', models.DateTimeField(default=django.utils.timezone.now)),
                ('coor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clima.Coordenadas', verbose_name='Coordenadas')),
                ('medicion_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clima.Medicion', verbose_name='Medicion')),
            ],
        ),
    ]
